import { CheatCategory } from '../shared/CheatSheetView';

export const GIT_CATEGORIES: CheatCategory[] = [
  {
    id: 'setup',
    title: 'Setup & Config',
    commands: [
      { keys: 'git init', desc: 'Initialize a new repository' },
      { keys: 'git clone <url>', desc: 'Clone a repository' },
      { keys: 'git config --global user.name "Name"', desc: 'Set your name for commits' },
      { keys: 'git config --global user.email "email"', desc: 'Set your email for commits' },
      { keys: 'git config --list', desc: 'List all config settings' },
      {
        keys: 'git config --global core.editor "code --wait"',
        desc: 'Set VS Code as the default editor',
      },
    ],
  },
  {
    id: 'staging',
    title: 'Staging & Committing',
    commands: [
      { keys: 'git status', desc: 'Show the working tree status' },
      { keys: 'git add <file>', desc: 'Stage a file' },
      { keys: 'git add .', desc: 'Stage all changes in the current directory' },
      { keys: 'git add -A', desc: 'Stage all changes, including deletions' },
      { keys: 'git rm <file>', desc: 'Remove a file and stage the deletion' },
      { keys: 'git mv <old> <new>', desc: 'Rename/move a file and stage it' },
      { keys: 'git commit -m "message"', desc: 'Commit staged changes' },
      { keys: 'git commit -am "message"', desc: 'Stage all tracked files and commit' },
      { keys: 'git commit --amend', desc: "Edit the last commit's message or contents" },
      {
        keys: 'git commit --amend --no-edit',
        desc: 'Add staged changes to the last commit, keep its message',
      },
    ],
  },
  {
    id: 'history',
    title: 'Inspecting Changes & History',
    commands: [
      { keys: 'git diff', desc: 'Show unstaged changes' },
      { keys: 'git diff --staged', desc: 'Show staged changes' },
      { keys: 'git log', desc: 'Show commit history' },
      { keys: 'git log --oneline', desc: 'Show condensed, one-line commit history' },
      { keys: 'git log --oneline --graph --all', desc: 'Show a visual graph of all branches' },
      { keys: 'git show <commit>', desc: "Show a commit's changes" },
      { keys: 'git blame <file>', desc: 'Show who last changed each line of a file' },
      { keys: 'git log -p <file>', desc: "Show a file's full change history" },
    ],
  },
  {
    id: 'branching',
    title: 'Branching',
    commands: [
      { keys: 'git branch', desc: 'List local branches' },
      { keys: 'git branch <name>', desc: 'Create a new branch' },
      { keys: 'git branch -d <name>', desc: 'Delete a branch (only if merged)' },
      { keys: 'git branch -D <name>', desc: 'Force-delete a branch' },
      { keys: 'git checkout <branch>', desc: 'Switch to a branch' },
      { keys: 'git checkout -b <branch>', desc: 'Create and switch to a new branch' },
      { keys: 'git switch <branch>', desc: 'Switch to a branch (modern alternative)' },
      { keys: 'git switch -c <branch>', desc: 'Create and switch to a new branch (modern)' },
      { keys: 'git branch -m <new-name>', desc: 'Rename the current branch' },
    ],
  },
  {
    id: 'merging',
    title: 'Merging & Rebasing',
    commands: [
      { keys: 'git merge <branch>', desc: 'Merge a branch into the current branch' },
      { keys: 'git merge --abort', desc: 'Abort a merge that has conflicts' },
      { keys: 'git rebase <branch>', desc: 'Reapply commits on top of another base branch' },
      { keys: 'git rebase -i HEAD~n', desc: 'Interactively rebase the last n commits' },
      { keys: 'git rebase --continue', desc: 'Continue a rebase after resolving conflicts' },
      { keys: 'git rebase --abort', desc: 'Cancel an in-progress rebase' },
      { keys: 'git cherry-pick <commit>', desc: 'Apply a specific commit onto the current branch' },
    ],
  },
  {
    id: 'remotes',
    title: 'Remotes',
    commands: [
      { keys: 'git remote -v', desc: 'List remotes and their URLs' },
      { keys: 'git remote add origin <url>', desc: 'Add a new remote' },
      { keys: 'git fetch', desc: 'Download objects and refs without merging' },
      { keys: 'git pull', desc: 'Fetch and merge from the remote' },
      { keys: 'git pull --rebase', desc: 'Fetch and rebase instead of merging' },
      { keys: 'git push', desc: 'Push commits to the remote' },
      { keys: 'git push -u origin <branch>', desc: 'Push and set the upstream branch' },
      {
        keys: 'git push --force-with-lease',
        desc: "Force-push safely (fails if the remote has others' new work)",
      },
    ],
  },
  {
    id: 'undoing',
    title: 'Undoing Changes',
    commands: [
      { keys: 'git restore <file>', desc: 'Discard unstaged changes to a file' },
      { keys: 'git restore --staged <file>', desc: 'Unstage a file, keep the changes' },
      { keys: 'git checkout -- <file>', desc: 'Discard unstaged changes (legacy syntax)' },
      { keys: 'git reset <file>', desc: 'Unstage a file (legacy syntax)' },
      { keys: 'git reset --soft HEAD~1', desc: 'Undo the last commit, keep changes staged' },
      { keys: 'git reset --mixed HEAD~1', desc: 'Undo the last commit, keep changes unstaged' },
      { keys: 'git reset --hard HEAD~1', desc: 'Undo the last commit and discard its changes' },
      { keys: 'git revert <commit>', desc: 'Create a new commit that undoes a commit' },
      { keys: 'git clean -fd', desc: 'Remove untracked files and directories' },
    ],
  },
  {
    id: 'stashing',
    title: 'Stashing',
    commands: [
      { keys: 'git stash', desc: 'Stash working directory changes' },
      { keys: 'git stash -u', desc: 'Stash including untracked files' },
      { keys: 'git stash list', desc: 'List all stashes' },
      { keys: 'git stash pop', desc: 'Apply and remove the latest stash' },
      { keys: 'git stash apply', desc: 'Apply the latest stash, keep it in the list' },
      { keys: 'git stash drop', desc: 'Delete the latest stash' },
      { keys: 'git stash show -p', desc: "Show a stash's diff" },
    ],
  },
  {
    id: 'tags',
    title: 'Tags',
    commands: [
      { keys: 'git tag', desc: 'List tags' },
      { keys: 'git tag <name>', desc: 'Create a lightweight tag' },
      { keys: 'git tag -a <name> -m "message"', desc: 'Create an annotated tag' },
      { keys: 'git push origin <tag>', desc: 'Push a single tag' },
      { keys: 'git push --tags', desc: 'Push all tags' },
      { keys: 'git tag -d <name>', desc: 'Delete a local tag' },
    ],
  },
  {
    id: 'searching',
    title: 'Comparing & Searching',
    commands: [
      { keys: 'git diff <branch1>..<branch2>', desc: 'Compare two branches' },
      { keys: 'git log --grep="text"', desc: 'Search commit messages' },
      { keys: 'git grep "text"', desc: 'Search the working tree for text' },
      { keys: 'git shortlog -sn', desc: 'Summarize commit counts by author' },
    ],
  },
];
