import { CheatCategory } from '../shared/CheatSheetView';

export const VIM_CATEGORIES: CheatCategory[] = [
  {
    id: 'modes',
    title: 'Modes & Basics',
    commands: [
      { keys: 'i', desc: 'Insert before the cursor' },
      { keys: 'a', desc: 'Insert (append) after the cursor' },
      { keys: 'I', desc: 'Insert at the start of the line' },
      { keys: 'A', desc: 'Insert (append) at the end of the line' },
      { keys: 'o', desc: 'Open a new line below and insert' },
      { keys: 'O', desc: 'Open a new line above and insert' },
      { keys: 'Esc / Ctrl-[', desc: 'Return to Normal mode' },
      { keys: 'v', desc: 'Enter Visual mode (character-wise)' },
      { keys: 'V', desc: 'Enter Visual Line mode' },
      { keys: 'Ctrl-v', desc: 'Enter Visual Block mode' },
      { keys: 'R', desc: 'Enter Replace mode' },
      { keys: ':', desc: 'Enter Command-line mode' },
      { keys: 'gi', desc: 'Insert at the last insert position' },
    ],
  },
  {
    id: 'movement',
    title: 'Movement',
    commands: [
      { keys: 'h j k l', desc: 'Move left, down, up, right' },
      { keys: 'w', desc: 'Jump to the start of the next word' },
      { keys: 'W', desc: 'Jump to the next WORD (whitespace-separated)' },
      { keys: 'b', desc: 'Jump to the start of the previous word' },
      { keys: 'B', desc: 'Jump to the previous WORD' },
      { keys: 'e', desc: 'Jump to the end of the word' },
      { keys: 'E', desc: 'Jump to the end of the WORD' },
      { keys: '0', desc: 'Jump to the start of the line' },
      { keys: '^', desc: 'Jump to the first non-blank character of the line' },
      { keys: '$', desc: 'Jump to the end of the line' },
      { keys: 'gg', desc: 'Go to the first line of the file' },
      { keys: 'G', desc: 'Go to the last line of the file' },
      { keys: '{n}G', desc: 'Go to line n' },
      { keys: 'Ctrl-f', desc: 'Page down (forward a full screen)' },
      { keys: 'Ctrl-b', desc: 'Page up (back a full screen)' },
      { keys: 'Ctrl-d', desc: 'Scroll down half a screen' },
      { keys: 'Ctrl-u', desc: 'Scroll up half a screen' },
      { keys: '}', desc: 'Jump to the next paragraph' },
      { keys: '{', desc: 'Jump to the previous paragraph' },
      { keys: '%', desc: 'Jump to the matching bracket/paren' },
      { keys: 'H', desc: 'Move cursor to top of screen' },
      { keys: 'M', desc: 'Move cursor to middle of screen' },
      { keys: 'L', desc: 'Move cursor to bottom of screen' },
      { keys: 'f{char}', desc: 'Jump to the next occurrence of char' },
      { keys: 'F{char}', desc: 'Jump to the previous occurrence of char' },
      { keys: 't{char}', desc: 'Jump to just before the next occurrence of char' },
      { keys: 'T{char}', desc: 'Jump to just after the previous occurrence of char' },
      { keys: ';', desc: 'Repeat the last f/t/F/T motion' },
      { keys: ',', desc: 'Repeat the last f/t/F/T motion, reversed' },
    ],
  },
  {
    id: 'editing',
    title: 'Editing & Deleting',
    commands: [
      { keys: 'x', desc: 'Delete the character under the cursor' },
      { keys: 'X', desc: 'Delete the character before the cursor' },
      { keys: 'dd', desc: 'Delete (cut) the current line' },
      { keys: 'D', desc: 'Delete from cursor to end of line' },
      { keys: 'dw', desc: 'Delete to the start of the next word' },
      { keys: 'cc', desc: 'Change (replace) the current line' },
      { keys: 'cw', desc: 'Change to the end of the word' },
      { keys: 'C', desc: 'Change from cursor to end of line' },
      { keys: 'r{char}', desc: 'Replace the character under the cursor' },
      { keys: '~', desc: 'Toggle case of the character under the cursor' },
      { keys: 'J', desc: 'Join the line below with the current line' },
      { keys: 'gJ', desc: 'Join lines without inserting a space' },
      { keys: 's', desc: 'Delete character(s) and enter Insert mode' },
      { keys: 'S', desc: 'Delete the line and enter Insert mode' },
    ],
  },
  {
    id: 'copypaste',
    title: 'Copy, Paste & Registers',
    commands: [
      { keys: 'yy / Y', desc: 'Yank (copy) the current line' },
      { keys: 'yw', desc: 'Yank to the start of the next word' },
      { keys: 'p', desc: 'Paste after the cursor / below the line' },
      { keys: 'P', desc: 'Paste before the cursor / above the line' },
      { keys: '"ayy', desc: 'Yank the current line into register a' },
      { keys: '"ap', desc: 'Paste the contents of register a' },
      { keys: '"+y', desc: 'Yank into the system clipboard' },
      { keys: '"+p', desc: 'Paste from the system clipboard' },
      { keys: ':reg', desc: 'List the contents of all registers' },
    ],
  },
  {
    id: 'undoredo',
    title: 'Undo, Redo & Repeat',
    commands: [
      { keys: 'u', desc: 'Undo the last change' },
      { keys: 'Ctrl-r', desc: 'Redo the last undone change' },
      { keys: 'U', desc: 'Undo all recent changes on one line' },
      { keys: '.', desc: 'Repeat the last change' },
    ],
  },
  {
    id: 'search',
    title: 'Search & Replace',
    commands: [
      { keys: '/pattern', desc: 'Search forward for pattern' },
      { keys: '?pattern', desc: 'Search backward for pattern' },
      { keys: 'n', desc: 'Repeat the last search, same direction' },
      { keys: 'N', desc: 'Repeat the last search, opposite direction' },
      { keys: '*', desc: 'Search forward for the word under the cursor' },
      { keys: '#', desc: 'Search backward for the word under the cursor' },
      { keys: ':%s/old/new/g', desc: 'Replace all occurrences in the file' },
      { keys: ':s/old/new/g', desc: 'Replace all occurrences on the current line' },
      { keys: ':%s/old/new/gc', desc: 'Replace all occurrences, asking for confirmation' },
      { keys: ':noh', desc: 'Clear search highlighting' },
    ],
  },
  {
    id: 'visual',
    title: 'Visual Mode',
    commands: [
      { keys: 'v', desc: 'Start character-wise selection' },
      { keys: 'V', desc: 'Start line-wise selection' },
      { keys: 'Ctrl-v', desc: 'Start block-wise selection' },
      { keys: 'o', desc: 'Move to the other end of the selection' },
      { keys: 'gv', desc: 'Reselect the last visual selection' },
      { keys: 'd / x', desc: 'Delete the selection' },
      { keys: 'y', desc: 'Yank the selection' },
      { keys: 'c', desc: 'Change the selection' },
      { keys: '> / <', desc: 'Indent / unindent the selection' },
      { keys: 'U / u', desc: 'Uppercase / lowercase the selection' },
    ],
  },
  {
    id: 'marks',
    title: 'Marks & Jumps',
    commands: [
      { keys: 'm{a-z}', desc: 'Set a mark at the cursor position' },
      { keys: "'{a-z}", desc: 'Jump to the line of a mark' },
      { keys: '`{a-z}', desc: 'Jump to the exact position of a mark' },
      { keys: "''", desc: 'Jump back to the position before the last jump' },
      { keys: 'Ctrl-o', desc: 'Jump to the older position in the jump list' },
      { keys: 'Ctrl-i', desc: 'Jump to the newer position in the jump list' },
    ],
  },
  {
    id: 'windows',
    title: 'Windows & Splits',
    commands: [
      { keys: ':split / Ctrl-w s', desc: 'Split the window horizontally' },
      { keys: ':vsplit / Ctrl-w v', desc: 'Split the window vertically' },
      { keys: 'Ctrl-w w', desc: 'Cycle to the next window' },
      { keys: 'Ctrl-w h/j/k/l', desc: 'Move to the window left/below/above/right' },
      { keys: 'Ctrl-w q', desc: 'Close the current window' },
      { keys: 'Ctrl-w =', desc: 'Make all windows equal size' },
      { keys: 'Ctrl-w _', desc: 'Maximize the current window height' },
    ],
  },
  {
    id: 'buffers',
    title: 'Buffers & Tabs',
    commands: [
      { keys: ':ls / :buffers', desc: 'List open buffers' },
      { keys: ':bnext / :bn', desc: 'Go to the next buffer' },
      { keys: ':bprev / :bp', desc: 'Go to the previous buffer' },
      { keys: ':b{n}', desc: 'Go to buffer number n' },
      { keys: ':bd', desc: 'Delete (close) the current buffer' },
      { keys: ':tabnew', desc: 'Open a new tab' },
      { keys: 'gt', desc: 'Go to the next tab' },
      { keys: 'gT', desc: 'Go to the previous tab' },
      { keys: '{n}gt', desc: 'Go to tab number n' },
    ],
  },
  {
    id: 'macros',
    title: 'Macros',
    commands: [
      { keys: 'q{a-z}', desc: 'Start recording a macro into a register' },
      { keys: 'q', desc: 'Stop recording' },
      { keys: '@{a-z}', desc: 'Play back a macro' },
      { keys: '@@', desc: 'Replay the last played macro' },
    ],
  },
  {
    id: 'formatting',
    title: 'Indenting & Formatting',
    commands: [
      { keys: '>>', desc: 'Indent the current line' },
      { keys: '<<', desc: 'Unindent the current line' },
      { keys: '==', desc: 'Auto-indent the current line' },
      { keys: 'gg=G', desc: 'Auto-indent the entire file' },
      { keys: 'gq{motion}', desc: "Reformat text to fit 'textwidth'" },
    ],
  },
  {
    id: 'files',
    title: 'File & Save',
    commands: [
      { keys: ':w', desc: 'Save the file' },
      { keys: ':q', desc: 'Quit (close window/buffer)' },
      { keys: ':wq / :x', desc: 'Save and quit' },
      { keys: ':q!', desc: 'Quit without saving' },
      { keys: ':wa', desc: 'Save all open files' },
      { keys: 'ZZ', desc: 'Save and quit (like :x)' },
      { keys: 'ZQ', desc: 'Quit without saving (like :q!)' },
    ],
  },
];
